# 0주차 ② NumPy 연습문제

**목표:** 배열의 **shape을 머릿속으로 예측**할 수 있게 되기. PyTorch 텐서는 NumPy 배열과 거의 똑같이 동작합니다.

| 파트 | 내용 | 추천 일정 |
|---|---|---|
| A | 배열 만들기와 shape | 4일차 |
| B | 인덱싱과 슬라이싱 | 5일차 |
| C | 연산, 브로드캐스팅, axis | 6일차 |
| D | NumPy에서 PyTorch로 | 6일차 |

**푸는 방법:** `None  # TODO` 자리를 채우고 실행한 뒤 채점 셀을 실행하세요.
**습관 들이기:** 코드를 실행하기 **전에** 결과 shape을 먼저 예측하고, 실행한 뒤 `print(x.shape)`로 확인하세요.

In [ ]:
# 준비 셀: 가장 먼저 실행하세요
import numpy as np
import torch
print("NumPy 버전:", np.__version__)

# 채점 도우미 (수정하지 마세요)
def check(test):
    try:
        test()
        print("✅ 정답!")
    except AssertionError as e:
        print("❌ 틀렸어요:", e)
    except Exception as e:
        print("❌ 아직 완성되지 않았어요:", type(e).__name__, e)

---
## 파트 A. 배열 만들기와 shape

```python
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape    # (2, 3)  → 2행 3열
a.ndim     # 2       → 차원 수 (= shape 의 길이)
a.size     # 6       → 원소 개수 (= 2*3)
```

자주 쓰는 생성 함수: `np.zeros((2, 3))`, `np.ones((2, 3))`, `np.arange(6)` (0~5), `np.random.rand(2, 3)`

### 문제 A-1. 배열 만들기

1. `a`: `[[1, 2, 3], [4, 5, 6]]`인 배열
2. `z`: 0으로 가득 찬 3행 4열 배열
3. `r`: `np.arange`와 `reshape`로 만든 `[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]`

In [ ]:
a = None  # TODO
z = None  # TODO
r = None  # TODO (힌트: np.arange(12).reshape(?, ?))

In [ ]:
def test():
    assert np.array_equal(a, [[1, 2, 3], [4, 5, 6]]), "a 가 달라요"
    assert z.shape == (3, 4) and (z == 0).all(), "z 는 0으로 가득 찬 (3, 4) 배열이어야 해요"
    assert np.array_equal(r, [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]), "r 이 달라요"

check(test)

### 문제 A-2. shape 예측 퀴즈 ★

**코드를 실행하지 말고** 머릿속으로 결과 shape을 예측해서 튜플로 적으세요. 다 적은 뒤 채점하세요.

| 변수 | 코드 |
|---|---|
| `q1` | `np.zeros((2, 3, 4)).shape` |
| `q2` | `np.arange(24).reshape(4, 6).shape` |
| `q3` | `np.arange(24).reshape(2, -1).shape` ← `-1`은 "나머지는 알아서 계산" |
| `q4` | `np.arange(24).reshape(2, 3, 4).reshape(-1).shape` |
| `q5` | `np.ones((32, 1, 28, 28)).reshape(32, -1).shape` ← MNIST 이미지 32장을 펼친 것 |

(`q4`처럼 원소가 하나뿐인 shape은 `(24,)`처럼 쉼표를 꼭 붙이세요.)

In [ ]:
q1 = None  # TODO 예: (1, 2, 3)
q2 = None
q3 = None
q4 = None
q5 = None

In [ ]:
def test():
    assert q1 == (2, 3, 4), "q1 틀림"
    assert q2 == (4, 6), "q2 틀림"
    assert q3 == (2, 12), "q3 틀림: 24개를 2행으로 나누면?"
    assert q4 == (24,), "q4 틀림: reshape(-1) 은 1차원으로 쭉 펼치기"
    assert q5 == (32, 784), "q5 틀림: 1*28*28 = ?"

check(test)

---
## 파트 B. 인덱싱과 슬라이싱

2차원 배열은 `a[행, 열]`로 접근합니다. `:`는 "전부", `a:b`는 "a부터 b 직전까지"입니다.

```python
a = np.arange(1, 13).reshape(3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a[0, 1]      # 2
a[1]         # [5 6 7 8]        → 1번 행 전체
a[:, 1]      # [ 2  6 10]       → 모든 행의 1번 열 (1차원이 됨!)
a[:, [1]]    # [[2] [6] [10]]   → 리스트로 감싸면 2차원 유지
a[:, :-1]    # 마지막 열만 빼고
```

### 문제 B-1. 원하는 부분 꺼내기

`a = np.arange(1, 13).reshape(3, 4)`에서 아래를 꺼내세요. **슬라이싱으로만** 해야 하고, 숫자를 직접 쓰면 안 됩니다.

| 변수 | 꺼낼 것 | 결과 |
|---|---|---|
| `row2` | 마지막 행 | `[9, 10, 11, 12]` |
| `col3` | 2번 열 (0부터 셈) | `[3, 7, 11]` |
| `block` | 가운데 아래 2×2 | `[[6, 7], [10, 11]]` |
| `rev` | 행 순서를 뒤집기 | `[[9..12], [5..8], [1..4]]` (힌트: `[::-1]`) |

In [ ]:
a = np.arange(1, 13).reshape(3, 4)

row2 = None   # TODO
col3 = None   # TODO
block = None  # TODO
rev = None    # TODO

In [ ]:
def test():
    assert np.array_equal(row2, [9, 10, 11, 12]), "row2 틀림"
    assert np.array_equal(col3, [3, 7, 11]), "col3 틀림"
    assert np.array_equal(block, [[6, 7], [10, 11]]), "block 틀림: 행 1~2, 열 1~2"
    assert np.array_equal(rev, [[9, 10, 11, 12], [5, 6, 7, 8], [1, 2, 3, 4]]), "rev 틀림"

check(test)

### 문제 B-2. 입력과 정답 나누기 ★ (시즌2 Lab 04-2와 똑같음)

아래 `data`는 학생 5명의 퀴즈 점수 3개와 기말 점수입니다. 각 행이 학생 한 명이고, **마지막 열이 정답(기말 점수)**입니다.

- `x_data`: 마지막 열을 뺀 나머지 → shape `(5, 3)`
- `y_data`: 마지막 열만, **2차원 유지** → shape `(5, 1)`

`y_data`가 `(5,)`가 아니라 `(5, 1)`이어야 하는 이유: 모델 출력이 `(5, 1)`이라서 shape을 맞춰야 오차 계산이 제대로 됩니다.

In [ ]:
data = np.array([[73, 80, 75, 152],
                 [93, 88, 93, 185],
                 [89, 91, 90, 180],
                 [96, 98, 100, 196],
                 [73, 66, 70, 142]], dtype=np.float32)

x_data = None  # TODO
y_data = None  # TODO
print(x_data.shape if x_data is not None else None, y_data.shape if y_data is not None else None)

In [ ]:
def test():
    assert x_data.shape == (5, 3), f"x_data shape 이 (5, 3) 이어야 해요 (지금: {x_data.shape})"
    assert y_data.shape == (5, 1), f"y_data shape 이 (5, 1) 이어야 해요 (지금: {y_data.shape}). [-1] 을 리스트로 감쌌나요?"
    assert y_data[0, 0] == 152, "y_data 의 첫 값이 152 여야 해요"

check(test)

### 문제 B-3. 조건으로 고르기 (불리언 인덱싱)

`scores`에서
- `high`: 80점 **초과**인 점수만 고르기
- `n_pass`: 60점 **이상**인 사람 수 (힌트: `True`는 1로 계산되므로 `.sum()`)
- `clipped`: 원본은 그대로 두고, 100점 초과를 100으로 바꾼 **복사본** (힌트: `.copy()`, 또는 `np.clip`)

In [ ]:
scores = np.array([55, 82, 91, 60, 47, 105, 78])

high = None     # TODO
n_pass = None   # TODO
clipped = None  # TODO

In [ ]:
def test():
    assert np.array_equal(high, [82, 91, 105]), "high 틀림"
    assert n_pass == 5, "n_pass 는 5여야 해요"
    assert np.array_equal(clipped, [55, 82, 91, 60, 47, 100, 78]), "clipped 틀림"
    assert scores[5] == 105, "원본 scores 가 바뀌면 안 돼요. .copy() 를 했나요?"

check(test)

---
## 파트 C. 연산, 브로드캐스팅, axis

### 원소별 곱 `*` vs 행렬곱 `@`
```python
A = np.array([[1, 2], [3, 4]])
A * A    # [[1, 4], [9, 16]]   → 같은 자리끼리 곱
A @ A    # [[7, 10], [15, 22]] → 행렬곱
```
행렬곱 `(n, k) @ (k, m)`의 결과는 `(n, m)`입니다. **가운데 k가 같아야** 합니다.

### axis
```python
x = np.array([[1, 2, 3],
              [4, 5, 6]])
x.sum(axis=0)   # [5, 7, 9]  → 위아래로 합침 (0번 축이 사라짐) → shape (3,)
x.sum(axis=1)   # [6, 15]    → 좌우로 합침 (1번 축이 사라짐) → shape (2,)
```
요령: **`axis=k`라고 하면 shape에서 k번째 숫자가 사라진다.**

### 문제 C-1. 선형회귀 가설 계산 ★ (시즌2 Lab 04-1)

선형회귀의 예측값은 $H(X) = XW + b$ 입니다.

- `X`: 학생 5명의 점수 3개 → `(5, 3)`
- `W`: 가중치 → `(3, 1)`
- `b`: 편향 (숫자 하나)

1. `H`: 예측값을 계산하세요. shape은 몇일까요?
2. `cost`: 평균제곱오차 $\frac{1}{m}\sum (H - y)^2$ (힌트: `np.mean`)

In [ ]:
X = data[:, :-1]                 # (5, 3)  B-2 의 data 재사용
y = data[:, [-1]]                # (5, 1)
W = np.array([[0.5], [0.5], [1.0]], dtype=np.float32)   # (3, 1)
b = 1.0

H = None     # TODO
cost = None  # TODO
print(H, cost)

In [ ]:
def test():
    assert H.shape == (5, 1), f"H 의 shape 은 (5, 1) 이어야 해요 (지금: {H.shape}). 원소별 곱 * 이 아니라 행렬곱 @ 을 썼나요?"
    assert abs(H[0, 0] - 152.5) < 1e-4, "첫 학생 예측값은 73*0.5 + 80*0.5 + 75*1.0 + 1 = 152.5 예요"
    assert abs(cost - np.mean((X @ W + b - y) ** 2)) < 1e-4, "cost 계산이 달라요"

check(test)

### 문제 C-2. axis 퀴즈

`m = np.arange(24).reshape(2, 3, 4)`일 때, 결과 shape을 **먼저 예측해서** 적고 채점하세요.

| 변수 | 코드 |
|---|---|
| `s1` | `m.sum(axis=0).shape` |
| `s2` | `m.sum(axis=1).shape` |
| `s3` | `m.sum(axis=2).shape` |
| `s4` | `m.mean(axis=2, keepdims=True).shape` ← `keepdims=True`는 사라질 축을 1로 남김 |

In [ ]:
s1 = None  # TODO
s2 = None
s3 = None
s4 = None

In [ ]:
def test():
    assert s1 == (3, 4), "s1 틀림: (2, 3, 4) 에서 0번째가 사라지면?"
    assert s2 == (2, 4), "s2 틀림"
    assert s3 == (2, 3), "s3 틀림"
    assert s4 == (2, 3, 1), "s4 틀림: keepdims=True 면 사라지는 대신 1이 남아요"

check(test)

### 문제 C-3. 브로드캐스팅으로 정규화하기

shape이 다른 배열끼리 연산하면 NumPy가 **작은 쪽을 자동으로 늘려서** 계산합니다. 이를 브로드캐스팅이라고 합니다.

```python
x = np.ones((3, 4))
x - np.array([1, 2, 3, 4])   # (3, 4) - (4,) → 각 행에서 [1,2,3,4] 를 뺌
```

딥러닝에서는 입력값의 범위를 맞추려고 **열(특징)마다 평균 0, 표준편차 1로 정규화**를 자주 합니다.

`feat`의 각 **열**에 대해 `(값 - 그 열의 평균) / 그 열의 표준편차`를 계산해 `normed`에 저장하세요. for문 없이 한 줄로 해야 합니다.

In [ ]:
feat = np.array([[170, 65],
                 [180, 80],
                 [160, 50],
                 [175, 70]], dtype=np.float64)   # (키, 몸무게) 4명

normed = None  # TODO (힌트: feat.mean(axis=?), feat.std(axis=?))
print(normed)

In [ ]:
def test():
    assert normed.shape == (4, 2), "shape 은 그대로 (4, 2) 여야 해요"
    assert np.allclose(normed.mean(axis=0), 0), "각 열의 평균이 0이 되어야 해요. axis 를 확인하세요"
    assert np.allclose(normed.std(axis=0), 1), "각 열의 표준편차가 1이 되어야 해요"

check(test)

### 문제 C-4. 분류 결과 채점하기 ★ (모든 분류 실습에서 매번 나옴)

모델이 이미지 5장에 대해 3개 클래스의 점수를 냈습니다 (`logits`, shape `(5, 3)`).

1. `pred`: 각 이미지에서 **점수가 가장 큰 클래스 번호** (힌트: `argmax`, axis는?) → shape `(5,)`
2. `acc`: 정답 `labels`와 비교한 정확도 (0~1 사이 숫자). 힌트: `(pred == labels).mean()`

In [ ]:
logits = np.array([[2.0, 0.1, 0.3],
                   [0.2, 1.5, 0.1],
                   [0.1, 0.2, 3.0],
                   [1.2, 1.1, 0.0],
                   [0.0, 0.5, 0.4]])
labels = np.array([0, 1, 2, 1, 1])

pred = None  # TODO
acc = None   # TODO
print(pred, acc)

In [ ]:
def test():
    assert np.array_equal(pred, [0, 1, 2, 0, 1]), "pred 틀림: 각 행(이미지)마다 최댓값 위치 → axis=1"
    assert abs(acc - 0.8) < 1e-9, "5개 중 4개 맞았으니 acc 는 0.8 이에요"

check(test)

### 문제 C-5. one-hot 인코딩

정답 번호를 "해당 위치만 1, 나머지는 0"인 벡터로 바꾸는 것을 **one-hot**이라고 합니다. 예를 들어 클래스가 4개일 때 `2`는 `[0, 0, 1, 0]`입니다.

`labels`를 one-hot으로 바꿔 `onehot`(shape `(4, 4)`)에 저장하세요.
힌트: `np.eye(4)`는 4×4 단위행렬이고, 그 행들이 바로 one-hot 벡터입니다. 정수 배열로 인덱싱하면 여러 행을 한 번에 꺼낼 수 있습니다.

In [ ]:
labels = np.array([2, 0, 3, 1])

onehot = None  # TODO
print(onehot)

In [ ]:
def test():
    assert onehot.shape == (4, 4), "shape 이 (4, 4) 여야 해요"
    assert np.array_equal(onehot.argmax(axis=1), labels), "각 행의 1 위치가 labels 와 같아야 해요"
    assert onehot.sum() == 4, "각 행에 1이 딱 하나씩만 있어야 해요"

check(test)

---
## 파트 D. NumPy에서 PyTorch로

PyTorch 텐서는 NumPy와 거의 같습니다. 이름이 조금 다른 것만 기억하면 됩니다.

| NumPy | PyTorch |
|---|---|
| `np.array(...)` | `torch.tensor(...)` |
| `a.shape` | `t.shape` 또는 `t.size()` |
| `a.reshape(2, -1)` | `t.view(2, -1)` 또는 `t.reshape(2, -1)` |
| `a.sum(axis=0)` | `t.sum(dim=0)` |
| `a.argmax(axis=1)` | `t.argmax(dim=1)` |
| `a @ b` | `t @ u` 또는 `t.matmul(u)` |
| 서로 변환 | `torch.from_numpy(a)`, `t.numpy()` |

**PyTorch만 가진 기능:** GPU 계산(`.to('cuda')`)과 **자동 미분**(`requires_grad=True`, `.backward()`).

### 문제 D-1. 같은 계산을 PyTorch로

C-1과 C-4를 PyTorch로 다시 해보세요.
1. `Xt`, `yt`, `Wt`: `X`, `y`, `W`를 `torch.from_numpy`로 변환
2. `Ht`: `Xt @ Wt + b`
3. `pred_t`: `logits`를 텐서로 바꾼 뒤 `argmax(dim=1)`

In [ ]:
Xt = None      # TODO
yt = None      # TODO
Wt = None      # TODO
Ht = None      # TODO
pred_t = None  # TODO

In [ ]:
def test():
    assert isinstance(Ht, torch.Tensor), "Ht 는 torch.Tensor 여야 해요"
    assert Ht.shape == (5, 1), "Ht 의 shape 은 (5, 1)"
    assert np.allclose(Ht.numpy(), H), "NumPy 로 계산한 H 와 같아야 해요"
    assert pred_t.tolist() == [0, 1, 2, 0, 1], "pred_t 틀림"

check(test)

### 문제 D-2. 맛보기: 자동 미분으로 W 한 번 업데이트하기

시즌2 Lab 02~03에서 할 내용의 미리보기입니다. 지금은 흐름만 보면 됩니다.

1. `W`를 `requires_grad=True`인 텐서로 만들면 PyTorch가 계산 과정을 기억합니다.
2. `cost.backward()`를 부르면 `W.grad`에 **cost를 줄이려면 W를 어느 방향으로 바꿔야 하는지**(기울기)가 계산됩니다.
3. `W`에서 `lr * W.grad`를 빼면 cost가 줄어듭니다. 이게 **경사하강법**입니다.

아래 셀의 `TODO` 두 줄만 채우고, cost가 줄어드는지 확인하세요. (**D-1을 먼저 풀어야** `Xt`, `yt`가 있어서 실행됩니다.)

In [ ]:
Wg = torch.zeros((3, 1), requires_grad=True)
bg = torch.zeros(1, requires_grad=True)
lr = 1e-5

cost_before = torch.mean((Xt @ Wg + bg - yt) ** 2)
cost_before.backward()              # 기울기 계산 → Wg.grad, bg.grad 에 저장됨

with torch.no_grad():               # 업데이트 자체는 미분 기록에서 제외
    Wg -= None  # TODO: lr * Wg.grad
    bg -= None  # TODO: lr * bg.grad

cost_after = torch.mean((Xt @ Wg + bg - yt) ** 2)
print("업데이트 전 cost:", cost_before.item())
print("업데이트 후 cost:", cost_after.item())

In [ ]:
def test():
    assert cost_after.item() < cost_before.item(), "업데이트 후 cost 가 줄어야 해요"

check(test)

---
## 마무리 자가 점검

- [ ] `np.zeros((3, 4))[:, 1:3].shape`을 바로 답할 수 있다 → `(3, 2)`
- [ ] `a[:, -1]`과 `a[:, [-1]]`의 shape 차이를 설명할 수 있다
- [ ] `axis=0`과 `axis=1`이 각각 무엇을 합치는지 설명할 수 있다
- [ ] `(5, 3) @ (3, 1)`의 결과 shape을 안다
- [ ] 분류 결과에서 `argmax`로 예측을 뽑고 정확도를 계산할 수 있다

다 체크되면 **0주차 완료**입니다. 1주차(시즌1 Lec 1~2 + 시즌2 Lab 01~02)로 넘어가세요.
Lab 01 텐서 조작 노트북이 이번 노트북과 거의 같은 내용이라 훨씬 쉽게 느껴질 겁니다.